version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=admin
      - DB_PASSWORD=admin
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
volumes:
  dev-db-data:
